import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Header from '../components/Header'

const Home: NextPage = () => {
  return (
    <div className='___gatsby'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{outline: "none"}} tabIndex={-1} id='gatsby-focus-wrapper'>
        <div className="kuda-entry white kuda-page--transition">
          <div className="kuda-entry--wrap">
            {/*header component */}
            <Header />
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
