import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.gatsby}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.gatsby_focus_wrapper}>
        <div className={styles.kuda_entry}>
            <div className={styles.kuda_entry__wrap}></div>
        </div>
      </main>
    </div>
  )
}

export default Home
